Wheels: support pocl_binary_distribution
inducer/pyopencl pull request #275
Opened 2019-02-15 00:30 UTC by isuruf

Scripts for building pocl are at https://github.com/isuruf/pocl-binary-distribution.

cc @gmagno

2019-02-15 01:13 UTC, isuruf commented
still a WIP. Pocl doesn't work properly

2019-02-15 05:36 UTC, isuruf commented
Ready for a review now. There's one catch. `pyopencl` and `pocl-binary-distribution` have to be installed side-by-side. Otherwise `pyopencl` will not see `pocl`

2019-03-08 16:10 UTC, isuruf commented
Ping. Added suport for `pyopencl[oclgrind]` as well.

2019-03-08 16:52 UTC, inducer requested changes
Could you also hack the docs (`docs/misc.rst`) to highlight this as an alternate install option?

2019-03-08 16:52 UTC, inducer commented on travis/build-wheels.sh
> +    exit 0
Could you add a message here, to avoid confusion on why there's no upload?

2019-03-08 23:49 UTC, inducer approved these changes

2019-03-08 23:49 UTC, inducer commented
Thanks @isuruf!

2019-03-08 23:50 UTC, merged

2019-03-08 23:52 UTC, inducer commented
Releasing 2018.2.5 mainly as an excuse to get these wheels out there.

2019-03-09 01:05 UTC, isuruf commented
Looks like it worked. `pip install "pyopencl[pocl, oclgrind]"` gave me 2 working opencl implementations.

2019-03-09 01:09 UTC, inducer commented
There are wheels! https://pypi.org/project/pyopencl/2018.2.5/#files

@gmagno @isuruf Could you check that they work?

And the docs got updated: https://documen.tician.de/pyopencl/misc.html#installing-from-pypi-with-linux-wheels

I wonder whether we should promote wheels first--i.e. move that above the conda-based method.

2019-03-09 01:11 UTC, inducer commented
@isuruf (a) you beat me to it! :) :+1: 
(b) This is so cool. Thanks for working on this.

2019-03-09 02:21 UTC, gmagno commented
oh man, this is great! :rocket: 
It looks good on my system.

![image](https://user-images.githubusercontent.com/46817915/54064973-cb4c9780-41f8-11e9-8a57-f360537a97f3.png)